### ISSUE TITLE
Blocks of code as macro args

### ISSUE THREAD

**Issue by colesico** [badlogic/basis-template#18]
Is it possible to pass code blocks to macros, not just string / literal values? Such is needed to create complex reusable components, layouts

**Comment by badlogic** [comment]
You can not pass one macro to another I'm afraid. You can pass
functions/methods via the context, and pass these to macros though.

**Comment by badlogic** [comment]
If you want to do something like components, i'd suggest to create one
template per component. You can then include those templates in other
templates.

**Comment by colesico** [comment]
Ok one separate tmpl per component:

<div>{{val}}<div>

val must be passed to that tmpl as <p>{{ button('ok') }}<p>

how can I define this in parent template?

**Comment by badlogic** [comment]
You can't.

**Comment by colesico** [comment]
Such functionality is widely used in template engines such as vuejs (with slots), twig (with embed)...Is it planned to implement such a functionality in the future?

**Comment by badlogic** [comment]
I'm afraid there is no plan for functionality going beyond what the various
include statements of basis-template provide.
