### ISSUE TITLE
String-only engine

### ISSUE THREAD

**Issue by Jelledb** [badlogic/basis-template#22]
Hi,

We started using this templating engine, and we're very satisfied with how it works.
However, we are looking for something that just accepts strings and not files/paths.

I was wondering if it is possible to use it only with strings, and skip the whole path part. We currently have a bit of a hacky solution for this problem.

**Comment by badlogic** [comment]
Paths are required for the include feature. You can create templates from
Java strings via the MapTemplateLoader, specifying whatever path you deem
appropriate. See
https://github.com/badlogic/basis-template/blob/master/src/test/java/io/marioslab/basis/template/InterpreterTest.java#L53
